### ISSUE TITLE
Improve compatibility with RCP core export file

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-csv-user-import#10]
There's a mismatch in what this plugin looks for in column headers and what RCP exports.

For example, RCP exports the user email data to a column with a header of `User Email`. This plugin looks for `user_email`, so it doesn't work with the RCP export file without renaming all the headers.

It would be great for this to work out of the box without any edits.

**Comment by pippinsplugins** [comment]
Yes yes yes.

**Comment by nosegraze** [comment]
Related, but I like how EDD's importer works where you can map fields yourself and see a preview.

**Comment by nosegraze** [comment]
> Related, but I like how EDD's importer works where you can map fields yourself and see a preview.

I'm splitting this off into a new issue https://github.com/restrictcontentpro/rcp-csv-user-import/issues/26

I think we should hurry up and adjust the headers now and maybe consider the field mapping at a later time, like maybe when we get batch processing. I've gotten a few more support tickets where people have been confused about this header mismatch so I just think we should hurry up and get it fixed.

**Comment by nosegraze** [comment]
PR: #29
