### ISSUE TITLE
Don't allow to set "active" status for free levels

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-csv-user-import#28]
We get a lot of customers who don't understand that members of a free level should be set to "Free" instead of "Active". When they import users, they set the status to "Active" naturally, or perhaps they don't even bother clicking the dropdown to see that "Free" is available because it defaults to "Active" and that seems right too.

This has caused a few issues, such as subscriber counts being incorrect in the `Subscription Levels` table. If the subscription level is free, then RCP counts the members with a `free` status. I had one customer who had 188 `active` members on a free level and didn't understand why the subscribers count in the table was `0`. Another customer had a problem with Group Accounts when making the same mistake.

Perhaps if a free subscription level is selected, we should auto switch the status dropdown to `Free` and grey it out. If necessary, we could have an "Edit" link to re-enable the dropdown but show a warning/message when they click that.

**Comment by nosegraze** [comment]
PR: #34

![rcp-csv-import-free-status](https://user-images.githubusercontent.com/6324272/34990283-7af2d5d4-fabd-11e7-8737-622e1f4cb6a0.png)

**Comment by mindctrl** [comment]
Works great! What do you think about auto changing the status back to Active if someone moves from a free level to an active level? Would be helpful if the first level is free and they change it to a paid one, and also helpful in cases where someone selects a free one by mistake and then changes it.

**Comment by nosegraze** [comment]
I'm good with that! I'll update shortly.
