### ISSUE TITLE
Add option to disable emails

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-csv-user-import#37]
Right now there's a discrepancy in how emails work. If you import members with a status of `active`, they will not get an email. This is due to the `_rcp_new_subscription` check in RCP core's `rcp_email_on_activation()` function.

If you import them as `free`, they will get an email.

Regardless of what we do in core, it would be nice to have an option here to disable emails from going out.

**Comment by nosegraze** [comment]
PR: #41
