### ISSUE TITLE
Imported members not given subscription level role

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-csv-user-import#38]

**Comment by nosegraze** [comment]
PR: #40

I updated the add-on to use the `rcp_add_user_to_subscription()` function for setting all the subscription details. This majorly simplifies the code and handles as few things automatically, including setting the correct role.

If the user isn't on RCP `2.9`+ then I keep the old code. I edited that to include setting the role manually.

**Comment by GitHubGreg** [comment]
I stumbled upon this issue while searching something similar. When I use rcp_add_user_to_subscription to modify users after new user creation (not using the CSV import add-on, just a regular user creation) the Subscriber role is missing from the newly-created user. Is this related to this bug?

**Comment by mindctrl** [comment]
@GitHubGreg open a ticket here with the code you're using and we'll take a closer look: https://restrictcontentpro.com/support/

**Comment by GitHubGreg** [comment]
Ok done, thanks.
