### ISSUE TITLE
Verify required user fields exist in the CSV row before creating the user account

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-csv-user-import#47]
I ran into a weird issue where a BOM character caused the email check to fail here: https://github.com/restrictcontentpro/rcp-csv-user-import/blob/1.1.8/rcp-user-import.php#L201

The user account was created without an email address, because WP core does not require it when doing it programmatically with `wp_insert_user()`. This caused a chain reaction of weird bugs with the import and in other plugins, like EDD.

We should verify that all the _required_ fields for a user account are there before running `wp_insert_user()`.

**Comment by mindctrl** [comment]
Just had another ticket with this issue.

Newer versions of the ParseCsv lib stripe BOM characters.

https://github.com/parsecsv/parsecsv-for-php/blob/063a812732e6d4f9dd94b132b1c463b245130222/src/Csv.php#L908

However it require PHP 5.5 and up. We may not even need this library though. PHP has its own CSV parsing functions, and the readme even recommends trying those first.

> You may not need a library at all: before using ParseCsv, please make sure if PHP's own str_getcsv(), fgetcvs() or fputcsv() meets your needs.

I recently used PHP's built in functions without any issues, so something to consider in RCP core https://github.com/restrictcontentpro/restrict-content-pro/issues/1805.

**Comment by nosegraze** [comment]
PR: #50
