### ISSUE TITLE
RCP 3.0 integration

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-csv-user-import#59]
# 3.0
- [x] Use new `rcp_add_customer()` and `rcp_add_membership()` functions.
- [x] Update `rcp_set_status` actions.
- [x] Maintain backwards compat with < 3.0.

# 3.1 - multiple memberships
- [ ] Maybe add an option that allows users to specify what happens if they try importing a user that already has a membership -- should the existing membership be changed/replaced, or should a second membership be added in addition to what's already there?

**Comment by nosegraze** [comment]
PR: #60

@misulicus Can you please test this with RCP version 3.0 (`release/3.0` branch)? Here's the expected behaviour:

- If importing a user that doesn't already exist: they should have a user account created, a customer record created (Restrict > Customers), and a brand new membership record created (Restrict > Memberships) with all the correct data.
- If importing a user that already exists and has a membership, one of two things should happen:
    1. If the current membership is for the same membership level as the imported one, then the existing membership record will be edited.
    2. If the current membership is for a different membership level, then this membership will be cancelled (and deleted in the sense that you won't see it in the admin panel), and a new one will be created instead.

Most importantly, all the data should be correct.

**Comment by misulicus** [comment]
the included sample.csv file is ok to use to test data ?

**Comment by nosegraze** [comment]
Yep that's fine!
