### ISSUE TITLE
Failing when User Login exists already but different email is imported

### ISSUE THREAD

**Issue by misulicus** [restrictcontentpro/rcp-csv-user-import#64]
After a long ticket i was finally able to get instructions on how to replicate this scenario from the customer:
https://secure.helpscout.net/conversation/861057856/121357?folderId=2314937

```
1. Take any existing user with a given first name, last name, username, and email.
2. Use the CSV Import plugin to import a user with an identical username to #1 but different email. First and last name may be similar or different. Do not include user ID or any other fields.
3. This will result in the new user not being imported, nor the existing user being updated, and (most importantly) no error message indicating a problem.
```

We don't seem to do any validation on the User Login field if it already exists

**Comment by nosegraze** [comment]
I think the best thing to do here is show an error message. Anything else is potentially dangerous because we'd be making assumptions with conflicting data.

**Comment by JJJ** [comment]
User account conflicts are tricky. Usernames aren’t really a good source of truth, and Email addresses are better, but not 100% guaranteed (as anyone who’s done support for us can attest to, lots of “individuals” use the same single email address to buy things from us.)

In my experience with the bbPress Converter, migrating millions of user accounts over the years, most site owners prefer to use the Email address as the “unique identifier” and then will resolve usernames & slugs manually as needed.

I’d recommend providing some way to easily query for “users that weren’t imported 100% cleanly.” Maybe a `rcp_import_error` key with some unique value to map to a plain-text explanation of the error. Was the username wrong? Did the email address already exist? Was their password unable to be converted? Etc...

**Comment by nosegraze** [comment]
Closing, as this has been accounted for in the new core importer: https://github.com/restrictcontentpro/restrict-content-pro/issues/1805
