### ISSUE TITLE
Accept only .csv files in CSV import dialog box

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/rcp-csv-user-import#9]
Taken from https://github.com/restrictcontentpro/rcp-group-accounts/issues/85:

> It's possible to select files that are not CSV files. A customer reported errors trying to upload a .numbers file. We can use the accept attribute to help people select the right file types. https://www.w3.org/TR/html5/forms.html#attr-input-accept

We should add this here as well.

**Comment by nosegraze** [comment]
PR: #19
